# Generated by Django 3.2.9 on 2021-11-29 01:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211129_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='category_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.photo'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
